Adding HW5_Tests_Practice
MarianaDrozd/Python-Martian-Manhunter-adv- pull request #4
Opened 2021-05-27 18:41 UTC by MarianaDrozd

2021-05-27 18:42 UTC, MarianaDrozd commented
![](https://github.trello.services/images/mini-trello-icon.png) [HW5 "Tests Practice" Mariana Drozd](https://trello.com/c/tnWjuw71/143-hw5-tests-practice-mariana-drozd)

2021-06-05 08:30 UTC, dimigor requested changes

2021-06-05 08:30 UTC, dimigor commented on homeworks/HW5_Tests_Practice/game.py
> +
залишай лише один порожній рядок в кінці

2021-06-05 08:30 UTC, dimigor commented on homeworks/HW5_Tests_Practice/test_game_by_pytest.py
> +def test_available_moves():
більше тестів, та зроби їх універсальнішими

2021-06-05 08:30 UTC, dimigor commented on homeworks/HW5_Tests_Practice/test_game_by_pytest.py
> +    assert game.board[5] != " "
не закладай різну логіку для одного тесту

2021-06-09 14:30 UTC, MarianaDrozd commented on homeworks/HW5_Tests_Practice/game.py
> +
залишила один пустий рядок, але запушилось ніби його нема (в мене в цьому файлі 108 рядків, а тут чомусь 107)

2021-06-11 13:25 UTC, dimigor approved these changes

2021-06-12 09:07 UTC, merged